# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3b52da68-b0ff-4ac6-9c50-a829ac9d4346";
      fsType = "ext4";
    };

  fileSystems."/storage/disk1" = {
    device = "/dev/disk/by-uuid/48c29eda-1805-4693-8372-1daf23796371";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "noatime"
      "nofail"
      "x-systemd.device-timeout=5s"
    ];
  };

  fileSystems."/storage/disk2" = {
    device = "/dev/disk/by-uuid/2b92485a-0050-4ca5-a530-1181e2c77f93";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "noatime"
      "nofail"
      "x-systemd.device-timeout=5s"
    ];
  };

  systemd.tmpfiles.rules = [
    "d /storage 0755 root root -"
    "d /storage/disk1 2770 root storage -"
    "a+ /storage/disk1 - - - - d:g::rwx,d:m:rwx,d:o:---"
    "d /storage/disk2 2770 root storage -"
    "a+ /storage/disk2 - - - - d:g::rwx,d:m:rwx,d:o:---"
  ];

  swapDevices =
    [ { device = "/dev/disk/by-uuid/04369620-2657-472c-ab25-40a9e88eabee"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
