{ pkgs, ... }:
let
  username = "david";
in
{
  # Set as trusted users for using mirrors
  nix.settings.trusted-users = [ username ];
  #
  # Define a user account.
  users.users."${username}" = {
    # the hashed password with salt is generated by run `mkpasswd`.
    # hashedPassword = "$y$j9T$taWQyCw5HrrBRkx8uNHO50$1DIFg45L4E3A9MhjeI4FenL2xNPHDkT5BBH/NtUwlp0";
    home = "/home/${username}";
    isNormalUser = true;
    shell = pkgs.zsh;
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILb6ayLkxFMHOMDSGcDWu2VgxIyK7Npll8OEBmXLaYGC d@D"
    ];
  };
}
