{ pkgs, ... }:
let
  username = "guest";
in
{
  # Define a user account.
  users.users."${username}" = {
    # the hashed password with salt is generated by run `mkpasswd`.
    hashedPassword = "$y$j9T$taWQyCw5HrrBRkx8uNHO50$1DIFg45L4E3A9MhjeI4FenL2xNPHDkT5BBH/NtUwlp0";
    home = "/home/${username}";
    isNormalUser = true;
    shell = pkgs.fish;
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMggbqyvwD9XXdwm/O9/aW8wx4k58hqM/08/gjnChS1b yang"
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3Rht6Gd3II72mYKGqpFeyljAT6suNiBwKUi/rai3sgW9ayyBaCRB3Uagfj2pGy3CKPPSw/vnkp7umcMnHN0QZwR0GfqmfSiW4DEOkbTSzJIf8qAJTT7nqL//jypzQ7vN3DuynazIh/PtPs+f84CDWeY71J8v8yRhFEn0yGvH6EOXuvuK0HGJLEwklSGLLNI0sy04WN3REkdHeut4fM8lp9OXqCODlX6mi8doWX3Awg46d/nfTuI2jiKY5JqlCKdyEIeeKQUHjZIbc2nsq1kLsWYqHGcJbKWHig8kwtqR1PTUNhUuiQ3CQE8reYvsGj4Ed/WqSdlOp6GO+ItY+PcVY7Io3u3inZbAv4OzUAsd6PDbaF7wQ6CzF5J2U+JiOhGaSYO1B/CKHFGb9TZAk9Rk+8GF5UPFHyDvuU0NXgeGgrMOgF93FqF7dtL6Px5EPl8YjKW6S2BDm7x7hQLYaUilOUNvk5Z8KqfzWG4uX1ke6XEVHNgY4co1fVjmVh/3mj1U= fiores@mylaptop"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILb6ayLkxFMHOMDSGcDWu2VgxIyK7Npll8OEBmXLaYGC d@D"
    ];
  };
}
